/**
 * Email reports for joiners and managers.
 */

function buildSessionReportData_(sessionId) {
  const session = getSessionById_(sessionId);
  if (!session) {
    throw new Error('Session not found: ' + sessionId);
  }

  const trainee = getTraineeByEmail_(session.traineeEmail);
  if (!trainee) {
    throw new Error('Trainee not found for session.');
  }

  const responses = getResponsesForSession_(sessionId);
  const questionsById = {};

  responses.forEach(function(r) {
    const q = getQuestionById_(r.questionId);
    if (q) {
      questionsById[r.questionId] = q;
    }
  });

  let totalFinal = 0;
  let maxPossible = 0;
  const breakdown = [];

  responses.forEach(function(r) {
    const q = questionsById[r.questionId] || {};
    const max = Number(r.aiMaxPoints) || Number(q.maxPoints) || 0;
    const score = effectiveScore_(r);
    totalFinal += score;
    maxPossible += max;

    breakdown.push({
      questionId: r.questionId,
      topic: q.topic || '',
      type: q.type || '',
      score: score,
      maxPoints: max,
      feedback: r.trainerFeedback || r.aiFeedback || '',
      improvements: r.aiImprovements || ''
    });
  });

  const pct = maxPossible > 0 ? Math.round((totalFinal / maxPossible) * 1000) / 10 : 0;
  const threshold = Number(getConfigValue_('pass_threshold_pct', ST_CONFIG.defaults.passThresholdPct)) || 70;
  const passed = pct >= threshold;

  return {
    session: session,
    trainee: trainee,
    responses: responses,
    breakdown: breakdown,
    totalFinal: totalFinal,
    maxPossible: maxPossible,
    pct: pct,
    threshold: threshold,
    passed: passed,
    improvementsSummary: session.improvementsSummary || buildImprovementsSummary_(responses, questionsById)
  };
}

function buildReportHtml_(report) {
  const trainee = report.trainee;
  const session = report.session;
  const statusLabel = report.passed ? 'Pass' : 'Needs improvement';
  const statusColor = report.passed ? '#12B76A' : '#D92D20';

  let breakdownHtml = report.breakdown.map(function(item) {
    return '<tr>' +
      '<td style="padding:8px;border-bottom:1px solid #E7E3F2;">' + escHtml_(item.questionId) + '</td>' +
      '<td style="padding:8px;border-bottom:1px solid #E7E3F2;">' + escHtml_(item.topic) + '</td>' +
      '<td style="padding:8px;border-bottom:1px solid #E7E3F2;">' + escHtml_(item.type) + '</td>' +
      '<td style="padding:8px;border-bottom:1px solid #E7E3F2;">' + item.score + ' / ' + item.maxPoints + '</td>' +
      '<td style="padding:8px;border-bottom:1px solid #E7E3F2;">' + escHtml_(item.feedback) + '</td>' +
      '</tr>';
  }).join('');

  const improvementsHtml = String(report.improvementsSummary || '')
    .split('\n')
    .filter(Boolean)
    .map(function(line) {
      return '<li style="margin-bottom:6px;">' + escHtml_(line.replace(/^•\s*/, '')) + '</li>';
    })
    .join('');

  return '<div style="font-family:Inter,Arial,sans-serif;color:#18181F;max-width:720px;">' +
    '<h1 style="color:#5F17F8;font-size:22px;">EOR Support Training — Week ' + session.week + ' Report</h1>' +
    '<p><strong>Trainee:</strong> ' + escHtml_(trainee.displayName) + ' (' + escHtml_(trainee.email) + ')</p>' +
    '<p><strong>Score:</strong> ' + report.totalFinal + ' / ' + report.maxPossible +
    ' (' + report.pct + '%) · <span style="color:' + statusColor + ';font-weight:600;">' + statusLabel + '</span></p>' +
    '<p><strong>Pass threshold:</strong> ' + report.threshold + '%</p>' +
    '<h2 style="font-size:16px;margin-top:24px;">Breakdown</h2>' +
    '<table style="width:100%;border-collapse:collapse;font-size:13px;">' +
    '<thead><tr style="background:#F8F7FC;">' +
    '<th style="text-align:left;padding:8px;">ID</th>' +
    '<th style="text-align:left;padding:8px;">Topic</th>' +
    '<th style="text-align:left;padding:8px;">Type</th>' +
    '<th style="text-align:left;padding:8px;">Score</th>' +
    '<th style="text-align:left;padding:8px;">Feedback</th>' +
    '</tr></thead><tbody>' + breakdownHtml + '</tbody></table>' +
    '<h2 style="font-size:16px;margin-top:24px;">Improvements</h2>' +
    '<ul style="padding-left:18px;">' + (improvementsHtml || '<li>No specific improvements recorded.</li>') + '</ul>' +
    '<p style="font-size:12px;color:#6B6578;margin-top:24px;">Generated by EOR Support Training App v' + ST_CONFIG.version + '</p>' +
    '</div>';
}

function escHtml_(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function sendFinalReportForSession_(sessionId, sentByEmail) {
  if (!isTrainer_(sentByEmail)) {
    throw new Error('Only trainers or sheet editors can send final reports.');
  }

  const report = buildSessionReportData_(sessionId);
  const html = buildReportHtml_(report);
  const subject = 'Training Week ' + report.session.week + ' — ' +
    report.trainee.displayName + ' (' + report.pct + '%)';

  const recipients = [report.trainee.email];
  if (report.trainee.managerEmail) {
    recipients.push(report.trainee.managerEmail);
  }

  MailApp.sendEmail({
    to: recipients.join(','),
    subject: subject,
    htmlBody: html
  });

  const totalFinal = report.totalFinal;
  updateSessionRow_(sessionId, {
    totalFinalScore: totalFinal,
    pctFinal: report.pct,
    passed: report.passed,
    status: 'final',
    reportSentAt: new Date()
  });
  updateResponseStatusesForSession_(sessionId, 'final', sentByEmail);

  return {
    ok: true,
    sessionId: sessionId,
    recipients: recipients,
    pct: report.pct,
    passed: report.passed
  };
}

function markSessionReviewed_(sessionId, reviewerEmail) {
  if (!isTrainer_(reviewerEmail)) {
    throw new Error('Only trainers or sheet editors can mark sessions reviewed.');
  }

  const session = getSessionById_(sessionId);
  if (!session) {
    throw new Error('Session not found.');
  }

  const responses = getResponsesForSession_(sessionId);
  let totalFinal = 0;
  let maxPossible = 0;

  responses.forEach(function(r) {
    totalFinal += effectiveScore_(r);
    maxPossible += Number(r.aiMaxPoints) || 0;
  });

  const pct = maxPossible > 0 ? Math.round((totalFinal / maxPossible) * 1000) / 10 : 0;
  const threshold = Number(getConfigValue_('pass_threshold_pct', ST_CONFIG.defaults.passThresholdPct)) || 70;

  updateSessionRow_(sessionId, {
    totalFinalScore: totalFinal,
    pctFinal: pct,
    passed: pct >= threshold,
    status: 'reviewed'
  });
  updateResponseStatusesForSession_(sessionId, 'reviewed', reviewerEmail);

  return { ok: true, sessionId: sessionId, pct: pct };
}
